services:
  dynamodb-local:
    image: amazon/dynamodb-local:2.5.2
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    working_dir: /home/dynamodblocal
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "/home/dynamodblocal/data"]
    volumes:
      - ./.dynamodb:/home/dynamodblocal/data
    restart: unless-stopped
